name: Musings of Sucess
favicon: null
layout_spectrum: 0.74685
typography_spectrum: 0.639
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#ffffff'
    - '#c8234a'
    - '#6460ab'
    - '#f36f21'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
