name: Musings of Sucess
favicon: null
layout_spectrum: 1
typography_spectrum: 0.639
title: The thoughts and wanderings of a former success
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8c8ca'
    - '#1a3f83'
    - '#2e0000'
    - '#ab837d'
    - '#953d33'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
