name: Musings of Sucess
favicon: null
layout_spectrum: 0.4644052619114518
typography_spectrum: 0.1392988080624491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5124483176041394
  lightness: 0.7802844292018563
  saturation: 0.07939389115199447
  rhythmicContrast: 0.9380703226197511
purpose: []
